### ISSUE TITLE
Reduce verbosity in RTSPConnection.js

### ISSUE THREAD

**Issue by rompeldunk** [medooze/rtsp-server#3]
RTSP-clients connecting to the RTSP-server is currently flooding the console with GET_PARAMETER responses, due to keep-alive requests.

Though useful for debug, we need an option to disable this, and this should be disabled by default.

Might I suggest an environment variable to enable this, and add a note about this in the README.md?

https://github.com/medooze/rtsp-server/blob/b343b5f55ab248e6d82d8d6d6a1517cf59ca093d/lib/RTSPConnection.js#L117

Add/replace this with something like:

```javascript

this.debug = process.env.RTSP_CONNECTION_DEBUG || false;

//To console if debug-mode
if (this.debug) {
    console.log("res: "+ str);
}

```

Edit: There might be multiple places one should be able to toggle this if you know of more places.

**Comment by murillo128** [comment]
added `debug` logs via https://github.com/medooze/rtsp-server/commit/4387853029583e874afae8f59431485feff8b07a
